import type { ImageCollectionItem, ShowCollectionItem } from "@/types";

const seedTimestamp = "2026-05-08T00:00:00.000Z";

export const fallbackImages: ImageCollectionItem[] = [
  {
    id: "image-neon-street",
    title: "夜景与霓虹街道",
    description: "城市夜景抓拍，偏赛博风格。",
    imageUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1200&q=80&auto=format&fit=crop",
    tags: ["城市", "夜景"],
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "image-seaside-sunset",
    title: "海边日落",
    description: "旅行途中拍摄，暖色氛围。",
    imageUrl: "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=1200&q=80&auto=format&fit=crop",
    tags: ["旅行", "自然"],
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "image-pink-building",
    title: "粉色公寓外墙",
    description: "像海报一样温柔的城市角落。",
    imageUrl: "https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200&q=80&auto=format&fit=crop",
    tags: ["建筑", "粉色"],
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "image-dessert-soda",
    title: "甜品与草莓气泡饮",
    description: "适合做个人收藏站里的气氛图。",
    imageUrl: "https://images.unsplash.com/photo-1464306076886-da185f6a9d05?w=1200&q=80&auto=format&fit=crop",
    tags: ["甜品", "夏日"],
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "image-tulip-field",
    title: "郁金香花田",
    description: "让页面看起来更像一本会发光的相册。",
    imageUrl: "https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=1200&q=80&auto=format&fit=crop",
    tags: ["花", "春天"],
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "image-neon-corner",
    title: "霓虹街角与电脑",
    description: "更偏未来感的收藏封面。",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80&auto=format&fit=crop",
    tags: ["霓虹", "科技"],
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];

export const fallbackShows: ShowCollectionItem[] = [
  {
    id: "show-the-bear",
    name: "The Bear",
    chineseTitle: "熊家餐馆",
    originalTitle: "The Bear",
    year: 2022,
    country: "US",
    genres: ["Drama", "Comedy"],
    carouselImages: [],
    rating: 9.1,
    posterUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1000&q=80&auto=format&fit=crop",
    summary: "围绕芝加哥小餐馆展开的高压成长故事。",
    recommendReason: "节奏极好，角色塑造扎实。",
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "show-dark",
    name: "Dark",
    chineseTitle: "暗黑",
    originalTitle: "Dark",
    year: 2017,
    country: "DE",
    genres: ["Sci-Fi", "Mystery"],
    carouselImages: [],
    rating: 8.9,
    posterUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1000&q=80&auto=format&fit=crop",
    summary: "围绕时间循环和家族秘密的悬疑故事。",
    recommendReason: "世界观复杂但严谨，适合二刷。",
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "show-breaking-bad",
    name: "Breaking Bad",
    chineseTitle: "绝命毒师",
    originalTitle: "Breaking Bad",
    year: 2008,
    country: "US",
    genres: ["Crime", "Drama"],
    carouselImages: [],
    rating: 9.5,
    posterUrl: "https://images.unsplash.com/photo-1542204165-65bf26472b9b?w=1000&q=80&auto=format&fit=crop",
    summary: "平凡老师一步步走向失控的经典剧集。",
    recommendReason: "节奏、人物和张力都非常强。",
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "show-stranger-things",
    name: "Stranger Things",
    chineseTitle: "怪奇物语",
    originalTitle: "Stranger Things",
    year: 2016,
    country: "US",
    genres: ["Sci-Fi", "Adventure"],
    carouselImages: [],
    rating: 8.7,
    posterUrl: "https://images.unsplash.com/photo-1522869635100-9f4b1e0a2a0a?w=1000&q=80&auto=format&fit=crop",
    summary: "怀旧、怪奇、少年冒险感很强的剧。",
    recommendReason: "封面氛围很适合做首页主视觉。",
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "show-sherlock",
    name: "Sherlock",
    chineseTitle: "神探夏洛克",
    originalTitle: "Sherlock",
    year: 2010,
    country: "UK",
    genres: ["Mystery", "Drama"],
    carouselImages: [],
    rating: 9.1,
    posterUrl: "https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?w=1000&q=80&auto=format&fit=crop",
    summary: "高密度推理与极强台词感的侦探剧。",
    recommendReason: "适合放在收藏页里做压轴展示。",
    isFeatured: true,
    status: "published",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
